services:
  - type: web
    name: VA
    env: docker
    branch: main
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        value: changeme123
      - key: DATABASE_URL
        fromDatabase:
          name: symfony-db
          property: connectionString
